#!/bin/bash
set -euo pipefail

SECRET_NAME="$BUILDKITE_PLUGIN_VAULT_SECRET_NAME"

echo "Setting VAULT format..."
export VAULT_FORMAT="${VAULT_FORMAT:-json}"

echo "Fetching secrets from Vault..."
secrets=$(vault kv get -field=data ci/${SECRET_NAME})

echo "Extracted secrets from Vault, setting environment variables..."
# Iterate through secrets and export them
for key in $(echo $secrets_json | jq -r 'keys[]'); do
    value=$(echo $secrets_json | jq -r --arg key "$key" '.[$key]')
    echo "Setting $key..."
    export $key=$value
done

echo "All secrets have been set as environment variables."

